### ISSUE TITLE
new-site.sh

### ISSUE THREAD

**Issue by nnachtegael** [evertramos/server-automation#5]
just a suggestion:
it will may be more 'user friendly' to change line 601 in new-site.sh
LOCAL_MYSQL_USER=${LOCAL_SITE_NAME:1:10}"_user"
with
LOCAL_MYSQL_USER=${LOCAL_SITE_NAME:**0**::10}"_user"

**Comment by evertramos** [comment]
Hello @nnachtegael you are definely right:

But should be like this:

```bash
LOCAL_MYSQL_USER=${LOCAL_SITE_NAME:0:10}"_user"
```

Care for a PR? Thanks!
